/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.d2bit.app2;

public final class Manifest {
    public static final class permission {
        public static final String MAPS_RECEIVE="com.d2bit.app2.permission.MAPS_RECEIVE";
    }
}
