/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.d2bit.app2;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int foo=0x7f020000;
        public static final int ic_action_next_item=0x7f020001;
        public static final int ic_action_previous_item=0x7f020002;
        public static final int ic_action_remove=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int icon_pointeres36=0x7f020005;
        public static final int icon_pointeres48=0x7f020006;
        public static final int icon_pointeres72=0x7f020007;
        public static final int icon_pointeres96=0x7f020008;
        public static final int old_icon=0x7f020009;
        public static final int splash320_480=0x7f02000a;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
